name: Cypress e2e tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      BUILD_PREFIX: true
      IS_MAIN: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm run start & npx wait-on --timeout 60000 http://localhost:3000

      - name: Run cypress tests
        continue-on-error: true
        run: npm run e2e:start

      - name: Generate cypress reports
        run: npm run report:merge && npm run report:generate

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: E2E report
          path: cypress/mochawesome-report
