name: Cypress e2e tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
        test-type:
          description: 'Device: (all/desktop/medium/small)'
          required: true
          default: 'desktop'
          options:
            - 'all'
            - 'desktop'
            - 'medium'
            - 'small'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      BUILD_PREFIX: true
      IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      CYPRESS_LOCKER_USER: ${{ secrets.CYPRESS_LOCKER_USER }}
      CYPRESS_PROBLEM_USER: ${{ secrets.CYPRESS_PROBLEM_USER }}
      CYPRESS_PERFORMANCE_GLITCH_USER: ${{ secrets.CYPRESS_PERFORMANCE_GLITCH_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm run start & npx wait-on --timeout 60000 http://localhost:3000

      - name: Run cypress tests
        continue-on-error: true
        run: npm run e2e:${{ github.event.inputs.test-type }}

      - name: Generate cypress reports
        run: npm run report:merge && npm run report:generate

      - name: Get tests execution results
        if: failure() || success()
        run: |
          PASSED_TESTS=$(node -e "console.log(require('./cypress/mochawesome/merged-report.json').stats.passes)")
          FAILED_TESTS=$(node -e "console.log(require('./cypress/mochawesome/merged-report.json').stats.failures)")
          SKIPPED_TESTS=$(node -e "console.log(require('./cypress/mochawesome/merged-report.json').stats.skipped)")
          DURATION_SECONDS=$(node -e "console.log(require('./cypress/mochawesome/merged-report.json').stats.duration)")
          HOURS=$((DURATION_SECONDS / 3600))
          MINUTES=$(( (DURATION_SECONDS % 3600) / 60 ))
          SECONDS=$((DURATION_SECONDS % 60))
          FORMATTED_DURATION=$(printf "%02d:%02d:%02d" $HOURS $MINUTES $SECONDS)
          echo "PASSED_TESTS=$PASSED_TESTS" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
          echo "SKIPPED_TESTS=$SKIPPED_TESTS" >> $GITHUB_ENV
          echo "FORMATTED_DURATION=$FORMATTED_DURATION" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: E2E report
          path: cypress/mochawesome

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK  }}
          SLACK_USERNAME: Cypress
          SLACK_TITLE: CI/CD E2E tests
          SLACK_MESSAGE: ":large_green_square: Passed: ${{ env.PASSED_TESTS  }} \n :large_red_square: Failed: ${{ env.FAILED_TESTS  }} \n :large_blue_square: Skipped: ${{ env.SKIPPED_TESTS  }} \n :alarm_clock: Duration: ${{ env.FORMATTED_DURATION  }}"
          SLACK_COLOR: ${{ job.status }}